# Generated by Django 5.1.1 on 2024-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(upload_to='watches/'),
        ),
    ]
