# Generated by Django 5.1.1 on 2024-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchApp', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
