# Generated by Django 5.0.2 on 2024-03-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=50)),
                ('leader', models.CharField(max_length=50)),
                ('advisor', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
