# Generated by Django 5.1.1 on 2024-10-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
