# Generated by Django 5.1.1 on 2024-10-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_hotel_image2_hotel_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='details',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
