# Generated by Django 5.1.1 on 2024-10-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0007_booking_total_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.IntegerField(),
        ),
    ]
