# Generated by Django 5.1.1 on 2024-10-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
