# Generated by Django 5.1.1 on 2024-10-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0011_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
